#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Adidastore11/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Adidastore11"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282131861788"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
export TIME="10"
if [[ ! -f /root/.isp ]]; then
curl -sS ipinfo.io/org?token=7a814b6263b02c > /root/.isp
fi
if [[ ! -f /root/.city ]]; then
curl -sS ipinfo.io/city?token=7a814b6263b02c > /root/.city
fi
if [[ ! -f /root/.myip ]]; then
curl -sS ipv4.icanhazip.com > /root/.myip
fi

export IP=$(cat /root/.myip);
export ISP=$(cat /root/.isp);
export CITY=$(cat /root/.city);
domain=$(cat /etc/xray/domain)
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
clear
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e " SSH Ovpn Account           "
echo -e "\033[1;93m---------------------------------------------------\033[0m"
read -p " Username : " Login
read -p " Password : " Pass
read -p " Limit IP     : " iplimit
read -p " Expired (Days) : " masaaktif
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/klmpk/limit/ssh/ip/
echo -e "$iplimit" > /etc/klmpk/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db

# Simpan ke database recovery
RECOVERY_DB="/etc/ssh/.ssh.db_recovery"
if [ ! -f "$RECOVERY_DB" ]; then
    touch "$RECOVERY_DB"
fi

# Hapus baris lama jika ada user yang sama
grep -vwE "^#ssh# $Login" "$RECOVERY_DB" > /tmp/.tempdb_recovery
mv /tmp/.tempdb_recovery "$RECOVERY_DB"

# Simpan ulang dengan status aktif
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expi} active" >> "$RECOVERY_DB"

clear

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>---------------------------------------------------</code>
<code>SSH OVPN Account     </code>
<code>---------------------------------------------------</code>
<code>Username         : </code> <code>$Login</code>
<code>Password         : </code> <code>$Pass</code>
<code>---------------------------------------------------</code>
<code>IP               : $IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Host Ns          : </code> <code>${NS}</code>
<code>Pub Key            : </code> <code>${PUB}</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port DNS          : 443, 53 ,22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>---------------------------------------------------</code>
<code>Port 80             : </code> <code>$domain:80@$Login:$Pass</code>
<code>Port 443             : </code> <code>$domain:443@$Login:$Pass</code>
<code>Port UDP             : </code> <code>$domain:1-65535@$Login:$Pass</code>
<code>Port UDP2            : </code> <code>$domain:1-7200@$Login:$Pass</code>
<code>Port UDP3            : </code> <code>$domain:1-7300@$Login:$Pass</code>
<code>Port UDP4            : </code> <code>$domain:1-10000@$Login:$Pass</code>
<code>---------------------------------------------------</code>
<code>Payload WSS      : </code><code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>---------------------------------------------------</code>
OVPN Download : https://$domain:81/
<code>---------------------------------------------------</code>
<code>Save Link Account: </code>https://$domain:81/ssh-$Login.txt
<code>---------------------------------------------------</code>
Aktif Selama         : $masaaktif Hari
Dibuat Pada          : $tnggl
Berakhir Pada        : $expe
<code>---------------------------------------------------</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
echo ""
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e " SSH OVPN Account    "
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e "Username         : $Login"
echo -e "Password         : $Pass"
echo -e "Limit Ip         : ${iplimit} User"
echo -e "Host             : $domain"
echo -e "Host Slowdns     : ${NS}"
echo -e "Pub Key          : ${PUB}"
echo -e "Location         : $CITY"
echo -e "ISP              : $ISP"
echo -e "Port OpenSSH     : 443, 80, 22"
echo -e "Port DNS         : 443, 53 ,22 "
echo -e "Port SSH UDP     : 1-65535,1-7200,1-7300,1-10000"
echo -e "Port Dropbear    : 443, 109 ,143"
echo -e "Port SSH WS      : 80,8080,8880,2086,2095"
echo -e "Port SSH SSL WS  : 443"
echo -e "Port SSL/TLS     : 443"
echo -e "Port OVPN WS SSL : 443"
echo -e "Port OVPN SSL    : 443"
echo -e "Port OVPN TCP    : 443, 1194"
echo -e "Port OVPN UDP    : 2200"
echo -e "BadVPN UDP       : 7100, 7300, 7300"
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e " Port 80 : $domain:80@$Login:$Pass"
echo -e " Port 443 : $domain:443@$Login:$Pass"
echo -e " Udp Custom : $domain:1-65535@$Login:$Pass"
echo -e " Udp Custom2 : $domain:1-7200@$Login:$Pass"
echo -e " Udp Custom3 : $domain:1-7300@$Login:$Pass"
echo -e " Udp Custom4 : $domain:1-10000@$Login:$Pass"
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e "Payload      : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e "OVPN Download    : https://$domain:81/"
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e "Save Link Account: https://$domain:81/ssh-$Login.txt"
echo -e "\033[1;93m---------------------------------------------------\033[0m"
echo -e "Aktif Selama     : $masaaktif Hari"
echo -e "Dibuat Pada      : $tnggl"
echo -e "Berakhir Pada    : $expe"
echo -e "----------------------------------------------------------------------"
echo -e "       Terima Kasih Telah Menggunakan     "
echo -e "            Premium Script                      "
echo -e "       Adidastore11 Tunneling             "
echo -e "----------------------------------------------------------------------"

hasil_ssh=$(cat <<EOF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      SSH OVPN Account
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Username        : $Login
Password        : $Pass
Limit IP        : ${iplimit} User
Host            : $domain
Host Slowdns    : ${NS}
Pub Key         : ${PUB}
Location        : $CITY
ISP             : $ISP

Port OpenSSH    : 443, 80, 22
Port DNS        : 443, 53, 22
Port SSH UDP    : 1-65535,1-7200,1-7300,1-10000
Port Dropbear   : 443, 109, 143
Port SSH WS     : 80, 8080, 8880, 2086, 2095
Port SSH SSL WS : 443
Port SSL/TLS    : 443
Port OVPN WS    : 443
Port OVPN SSL   : 443
Port OVPN TCP   : 443, 1194
Port OVPN UDP   : 2200
BadVPN UDP      : 7100, 7300, 7300

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Format Akun:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Port 80         : $domain:80@$Login:$Pass
Port 443        : $domain:443@$Login:$Pass
UDP Custom      : $domain:1-65535@$Login:$Pass
UDP Custom2     : $domain:1-7200@$Login:$Pass
UDP Custom3     : $domain:1-7300@$Login:$Pass
UDP Custom4     : $domain:1-10000@$Login:$Pass

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Payload:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OVPN Download   : https://$domain:81/
Save Link       : https://$domain:81/ssh-$Login.txt

Aktif Selama    : $masaaktif Hari
Dibuat Pada     : $tnggl
Berakhir Pada   : $expe
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Terima kasih telah menggunakan
      Premium Script
    Adidastore11 Tunneling
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
)

# Jangan tampilkan di terminal
# echo "$hasil_ssh"

# Simpan hasil ke file
[ -d "/root/home" ] || mkdir /root/home
echo "$hasil_ssh" > /root/home/ssh-$Login.txt