#!/bin/bash

log_file="/var/log/killusr.log"
echo "[ $(date) ] STARTED: killusr $1 $2" >> $log_file

# Fungsi penghapusan VMess
function delvm() {
    local user="$1"
    local exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting VMess user: $user ($exp)" >> $log_file

    sed -i "/^### ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/klmpk/limit/vmess/quota/${user}
    rm -f /etc/klmpk/limit/vmess/ip/${user}
    rm -f /etc/vmess/${user}
    rm -f /etc/limit/vmess/${user}
    rm -f /var/www/html/vmess-${user}.txt
    sed -i "/^### ${user} ${exp}/d" /etc/vmess/.vmess.db
    systemctl restart xray
}

# Fungsi VLess
function delvl() {
    local user="$1"
    local exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting VLess user: $user ($exp)" >> $log_file

    sed -i "/^#& ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/klmpk/limit/vless/quota/${user}
    rm -f /etc/klmpk/limit/vless/ip/${user}
    rm -f /etc/vless/${user}
    rm -f /etc/limit/vless/${user}
    rm -f /var/www/html/vless-${user}.txt
    sed -i "/^### ${user} ${exp}/d" /etc/vless/.vless.db
    systemctl restart xray
}

# Fungsi Trojan
function deltr() {
    local user="$1"
    local exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting Trojan user: $user ($exp)" >> $log_file

    sed -i "/^#! ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/klmpk/limit/trojan/quota/${user}
    rm -f /etc/klmpk/limit/trojan/ip/${user}
    rm -f /etc/trojan/${user}
    rm -f /etc/limit/trojan/${user}
    rm -f /var/www/html/trojan-${user}.txt
    sed -i "/^### ${user} ${exp}/d" /etc/trojan.trojan.db
    systemctl restart xray
}

# Fungsi Shadowsocks
function delss() {
    local user="$1"
    local exp=$(grep -w "^#!# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting SS user: $user ($exp)" >> $log_file

    sed -i "/^#!# ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/xray/limit/shadowsocks/quota/${user}
    rm -f /etc/xray/limit/shadowsocks/ip/${user}
    rm -f /etc/shadowsocks/${user}
    rm -f /etc/limit/shadowsocks/${user}
    rm -f /var/www/html/ss-${user}.txt
    sed -i "/^### ${user} ${exp}/d" /etc/.shadowsocks.db
    systemctl restart xray
}

# Fungsi SSH
function delssh() {
    local user="$1"

    echo "[ $(date) ] Deleting SSH user: $user" >> $log_file

    userdel -f ${user}
    rm -f /etc/xray/limit/ssh/ip/${user}
    rm -f /etc/ssh/${user}
    rm -f /var/www/html/ssh-${user}.txt
    sed -i "/^### ${user} /d" /etc/.ssh.db
    systemctl restart ws
    systemctl restart dropbear
}

# Fungsi NoobzVPNS
function delnoobz() {
    local user="$1"

    echo "[ $(date) ] Deleting Noobz user: $user" >> $log_file

    noobzvpns --remove-user ${user}
    sed -i "/^### $user/d" /etc/.noobz.db
    rm -f /var/www/html/noobzvpns-${user}.txt
    rm -f /etc/noobzvpns/${user}
    systemctl restart noobzvpns
}

# Eksekusi berdasarkan argumen
case "$1" in
  vm) delvm "$2" ;;
  vl) delvl "$2" ;;
  tr) deltr "$2" ;;
  ss) delss "$2" ;;
  ssh) delssh "$2" ;;
  nb) delnoobz "$2" ;;
  *)
    echo "[ $(date) ] Invalid or no action provided." >> $log_file
    ;;
esac